gantt
    title 老张 老六 老山
    dateFormat  YYYY-MM-DD
    section 老张
    吃饭           :a1, 2014-01-01, 30d
    睡觉           :after a1  , 20d
    打豆豆         :24d
    section 老六
    吃饭           :2014-01-1  , 12d
    睡觉           : 24d

    section 老山
    吃饭             :2014-01-1 ,11d
    睡觉             :12d
