C4Context
title 经济

Person(customerA, "政府")
Person(customerB, "产业")
Person_Ext(customerC, "劳工")
Person(customerD, "房子")


BiRel(customerA, customerB, "Uses")
BiRel(customerB, customerC, "Uses")
BiRel(customerC, customerD, "Uses")
BiRel(customerD, customerA, "Uses")

