* 文字
    写了很长时间的微博，然后莫名其妙的被销号了，这怎么能行了呢？首先我需要明白一点的是，如果我写的文字是要量化成钱的话，是需要写在自己的电脑上的，而不是其他地方。
    打小我就不是一个勇敢的人，我的愚蠢，无知倒是让自己走到了非正常人走的路了，拒绝成为一个劳动力的方法，找到了吗？需要自己的观众，需要自己事业。
    今天讨论很多的是当下的社会戾气的问题，各种极端事件频繁出现，历史也是如此吗？以前发展的时候是非人为的因素，现在是人开始变得暴戾了。中国当下社会底层的生存现状如何呢？城市化导致的结果是底层成为了城市的贫民了吗？城市和底层的财产关系。这是个要分析的问题，重点是那些看不见的数据。看不见的人。能在网络上发言的，我看还是没有成为社会的底层人群。
    ‘人性’这个词，到底是代表什么呢？中国的传统伦理统治，孔子的道德教化，法家的重刑主义。传统的中国对人性的思考可谓汗牛充栋，马克思的政治经济学，物质基础决定上层建筑。‘人性’这个词好像变得陌生，以及不可理解了。
    儒家的重农抑商
    基督的塔木德
    印度的种姓制度
    柏拉图的理想国
    中国的知识分子长期关注于中国的上层建筑，还有外国的知识分子长期关注的东西是什么呢？世界的真相是什么呢？到底谁才是最后的成功者呢？还是都要失败了呢？很讨厌的知识分子一天到晚什么也不做，而是去阴阳一些东西。法治是不是需要大力推广的呢？曾经好像是这样的，现在好像并不是了。
    
* 中东
** 沙特
* 近代史
** 英国的殖民扩张
*** 昂撒民族 大航海时代
**** 英国
**** 美国
***** 美国建国的历史
**** 澳大利亚
**** 新西兰
** 法国的殖民扩张
* 要做的事情
* 什么是政治？
** 我对中国政治的理解
1. 中国的历史有没有殖民扩张呢？
   如何理解中国的版图如此之大呢？汉人好像并不擅长殖民扩张，最后是文化认同然后成为了中国人，这个逻辑多少是现在很难理解的，而且西方的扩张主义到头来都是一场空。中国的传统文化是如何影响周围的民族的呢？特别是东南亚。
2. 现在发现的问题是其实我并不了解中国，或者是并不了解中国面临的问题是什么？
   现在想一下当年的文化大革命的文化是不是一场幻觉呢？扛着红旗反红旗。“文化大革命”的现实意义是什么呢？似乎并没有正面的影响，当一个革命的对象获取政权的时候，或者是一个革命派成为统治阶级的时候，面对的问题是什么呢？走向自己的反面。‘反者道之动’。统治阶级该如何继续革命呢？这好像到了一个死循环了，不合理成为了一种天然存在，底层注定是要被抛弃的。最后还是一个问题就是马克思主义千头万绪，就是两个子‘造反’。
3. 是时候分析其他的社会形态了
   英国的贵族为什么能延续如此长的时间呢？以及印度的社会形态延续了殖民宗主国的思路。西方的均势理论，东方的天下观。后毛时代成为了美国的附庸，导致的一个问题是自己的独立思考能力的丧失。
      
*** 毛时代的政治

1. 没人质疑毛的权力的合法性
2. 毛时代的大跃进，文化大革命


*** 政治的逻辑是什么呢？还应该是斗争哲学的逻辑。






*** 后毛时代的政治

1. 姓资姓社的问题，这是党的合法性问题，中毛共就是一个例子。
2. 经济发展好了，没有自信了。
   
多快好省，建设社会主义
造反有理
意识形态挂帅，保证走社会主义道路。

疆独
藏独
* 组织架构
党政军
中央政治局：战略方向
国务院
国防

* 去政治化

** 官僚主义

** 反腐

*** 市场下的腐败是什么样子的,


** 什么是时代的要求？
** DONE 制作一个视频[2024-08-13 Tue]
*** DONE 视频文本[2024-08-13 Tue]
*** 视频代码<2024-08-16 Fri>

什么是比较研究？

改革开放是什么？市场换技术。毛时代的技术引进。

科学技术是第一生产力。

唯生产力论
唯生产关系论


文物收藏 是一个金融行业吧。盛世古董，乱世黄金。




** TODO 制作一个网站[2024-08-13 Tue]
DEADLINE: <2024-08-16 Fri>

