graph LR;
      第一国际 --> 第二国际 --> 第三国际;
      巴黎公社 --> 十月革命;
      马克思 --> 列宁 --> 毛泽东--> 邓小平 --> 江泽民 --> 胡锦涛 --> 习近平;
      列宁 --> 斯大林 --> 赫鲁晓夫 -->  勃列日涅夫 --> 叶利钦 --> 戈尔巴乔夫;
      政府 --> 产业 --> 劳工 --> 必需品 --> 政府;
      朝鲜战争 --> 中印战争 --> 珍宝岛战役 --> 中越战争 --> 中美建交;
      中国工业化的历史 --> 朝鲜战争 --> 苏联转移重工业 --> 原子弹 --> 氢弹;


